---
title: "STAT 398 Project"
output: html_document
---

```{r}
Openers <- read.csv("/Users/HugoBelisario/Downloads/Northwestern University/2018-2019/Spring Quarter 2019/STAT 398 Spring Quarter 2019/Openers.csv")

Headliners <- read.csv("/Users/HugoBelisario/Downloads/Northwestern University/2018-2019/Spring Quarter 2019/STAT 398 Spring Quarter 2019/Headliners.csv")

summary(Openers$WPA)
summary(Headliners$WPA)

OpenersWPA <- lm(WPA ~ IP + BF + Openers$aLI, data=Openers)
summary(OpenersWPA)

HeadlinersWPA <- lm(WPA ~ IP + BF + Headliners$aLI, data=Headliners)
summary(HeadlinersWPA)

summary(Openers$ERA)
summary(Headliners$ERA)
```

Openers ANOVA

```{r}
OpenersANOVA <- data.frame(Openers$Player, Openers$Tm, Openers$ERA)

library(lme4)
OpenersERA.mod1 <- lmer(Openers$ERA ~ (1|Openers$Player), data=OpenersANOVA)
summary(OpenersERA.mod1)

sd(OpenersANOVA$Openers.ERA)

OpenersERA.mod2 <- lmer(Openers$ERA ~ (1|Openers$Player) + (1|Openers$Tm), data=OpenersANOVA)
summary(OpenersERA.mod2)

anova(OpenersERA.mod1, OpenersERA.mod2)
```

Headliners ANOVA

```{r}
HeadlinersANOVA <- data.frame(Headliners$Player, Headliners$Tm, Headliners$ERA)
HeadlinersANOVA
library(lme4)
HeadlinersERA.mod1 <- lmer(Headliners$ERA ~ (1|Headliners$Player), data=HeadlinersANOVA)
summary(HeadlinersERA.mod1)

sd(HeadlinersANOVA$Headliners.ERA)

HeadlinersERA.mod2 <- lmer(Headliners$ERA ~ (1 | Headliners$Player) + (1 | Headliners$Tm), data=HeadlinersANOVA)
summary(HeadlinersERA.mod2)

anova(HeadlinersERA.mod1, HeadlinersERA.mod2)
```

```{r}
Openers.est <- coef(OpenersERA.mod1)
Openers.est

Openers.means <- aggregate(Openers$ERA, list(Pitcher = Openers$Player), mean)
Openers.means

error <- Openers.means$x - Openers.est$`Openers$Player`
error

OpenersERA.rmse <- sqrt(sum(error)^2)
OpenersERA.rmse

Headliners.est <- coef(HeadlinersERA.mod1)
Headliners.est

Headliners.means <- aggregate(Headliners$ERA, list(Pitcher = Headliners$Player), mean)
Headliners.means

error2 <- Headliners.means$x - Headliners.est$`Headliners$Player`
error2

HeadlinersERA.rmse <- sqrt(sum(error2)^2)
HeadlinersERA.rmse

```

Runs Test

```{r}
RyanYarbrough <- read.csv("/Users/HugoBelisario/Downloads/Northwestern University/2018-2019/Spring Quarter 2019/STAT 398 Spring Quarter 2019/RyanYarbrough.csv")
RyanYarbrough
RyanYarbroughEarnedRuns <- c(1,2,0,1,1,3,4,4,1,2,2,6,5,0,1,3,3,1)
plot(RyanYarbroughEarnedRuns, type = "b", pch=19)
head(RyanYarbroughEarnedRuns)
median(RyanYarbroughEarnedRuns)
library(randtests)
runs.test(RyanYarbroughEarnedRuns)
print(acf(RyanYarbroughEarnedRuns))
Box.test(RyanYarbroughEarnedRuns, lag=12, type="L")

RyneStanekEarnedRuns <- c(0,2,0,0,0,0,0,3,0,2,0,0,0,0,0,2,3,0,0,0,0,3,0,1,0)
plot(RyneStanekEarnedRuns, type = "b", pch=19)
head(RyneStanekEarnedRuns)
median(RyneStanekEarnedRuns)
runs.test(RyneStanekEarnedRuns)
print(acf(RyneStanekEarnedRuns))
Box.test(RyneStanekEarnedRuns, lag = 12, type="L")
```

Openers

```{r}
SinglesOpeners <- Openers$H - Openers$HR - Openers$X3B - Openers$X3B

OpenerswOBA = ((0.690 * Openers$BB) + (0.720 * Openers$HBP) + (0.880 * SinglesOpeners) + (1.247 * Openers$X2B) + (1.578 * Openers$X3B) + (2.031 * Openers$HR)) / (Openers$AB + Openers$BB - Openers$IBB + Openers$SF + Openers$HBP)

OpenerswOBA

OpenerswOBA = ((0.690 * Openers$BB) + (0.720 * Openers$HBP) + (0.880 * SinglesOpeners) + (1.247 * Openers$X2B) + (1.578 * Openers$X3B) + (2.031 * Openers$HR)) / (Openers$AB + (Openers$BB - Openers$IBB) + Openers$SF + Openers$HBP)

Openers$wOBA <- OpenerswOBA
Openers$wOBA

summary(Openers$wOBA)
```

Headliners

```{r}
SinglesHeadliners <- Headliners$H - Headliners$HR - Headliners$X3B - Headliners$X3B

HeadlinerswOBA = ((0.690 * Headliners$BB) + (0.720 * Headliners$HBP) + (0.880 * SinglesHeadliners) + (1.247 * Headliners$X2B) + (1.578 * Headliners$X3B) + (2.031 * Headliners$HR)) / (Headliners$AB + Headliners$BB - Headliners$IBB + Headliners$SF + Headliners$HBP)

HeadlinerswOBA

HeadlinerswOBA = ((0.690 * Headliners$BB) + (0.720 * Headliners$HBP) + (0.880 * SinglesHeadliners) + (1.247 * Headliners$X2B) + (1.578 * Headliners$X3B) + (2.031 * Headliners$HR)) / (Headliners$AB + (Headliners$BB - Headliners$IBB) + Headliners$SF + Headliners$HBP)

Headliners$wOBA <- HeadlinerswOBA
Headliners$wOBA

summary(Headliners$wOBA)
```

Ryne Stanek

```{r}
SinglesRyneStanek <- RyneStanek$H - (RyneStanek$HR + RyneStanek$X3B + RyneStanek$X2B)

SinglesRyneStanek

RyneStanekwOBA = ((0.690 * RyneStanek$BB) + (0.720 * RyneStanek$HBP) + (0.880 * SinglesRyneStanek) + (1.247 * RyneStanek$X2B) + (1.578 * RyneStanek$X3B) + (2.031 * RyneStanek$HR)) / (RyneStanek$AB + (RyneStanek$BB - RyneStanek$IBB) + RyneStanek$SF + RyneStanek$HBP)

RyneStanek$wOBA <- RyneStanekwOBA
RyneStanek$wOBA

summary(RyneStanek$wOBA)

SinglesStanekNonOpener <- RyneStanekNonOpener$H - (RyneStanekNonOpener$HR + RyneStanekNonOpener$X3B + RyneStanekNonOpener$X2B)

SinglesStanekNonOpener

StanekNonOpenerwOBA = ((0.690 * RyneStanekNonOpener$BB) + (0.720 * RyneStanekNonOpener$HBP) + (0.880 * SinglesStanekNonOpener) + (1.247 * RyneStanekNonOpener$X2B) + (1.578 * RyneStanekNonOpener$X3B) + (2.031 * RyneStanekNonOpener$HR)) / (RyneStanekNonOpener$AB + (RyneStanekNonOpener$BB - RyneStanekNonOpener$IBB) + RyneStanekNonOpener$SF + RyneStanekNonOpener$HBP)

RyneStanekNonOpener$wOBA <- StanekNonOpenerwOBA
RyneStanekNonOpener$wOBA

summary(RyneStanekNonOpener$wOBA)
```

Ryan Yarbrough

```{r}
SinglesRyanYarbroughNonHeadliner <- RyanYarbroughNonHeadliner$H - (RyanYarbroughNonHeadliner$HR + RyanYarbroughNonHeadliner$X3B + RyanYarbroughNonHeadliner$X2B)

SinglesRyanYarbroughNonHeadliner

RyanYarbroughNonHeadlinerwOBA = ((0.690 * RyanYarbroughNonHeadliner$BB) + (0.720 * RyanYarbroughNonHeadliner$HBP) + (0.880 * SinglesRyanYarbroughNonHeadliner) + (1.247 * RyanYarbroughNonHeadliner$X2B) + (1.578 * RyanYarbroughNonHeadliner$X3B) + (2.031 * RyanYarbroughNonHeadliner$HR)) / (RyanYarbroughNonHeadliner$AB + RyanYarbroughNonHeadliner$BB - RyanYarbroughNonHeadliner$IBB + RyanYarbroughNonHeadliner$SF + RyanYarbroughNonHeadliner$HBP)

RyanYarbroughNonHeadliner$wOBA <- RyanYarbroughNonHeadlinerwOBA
RyanYarbroughNonHeadliner$wOBA

summary(RyanYarbroughNonHeadliner$wOBA)

SinglesRyanYarbrough <- RyanYarbrough$H - (RyanYarbrough$HR + RyanYarbrough$X3B + RyanYarbrough$X2B)

SinglesRyanYarbrough

RyanYarbroughwOBA = (0.690 * RyanYarbrough$BB + 0.720 * RyanYarbrough$HBP + 0.880 * SinglesRyanYarbrough + 1.247 * RyanYarbrough$X2B + 1.578 * RyanYarbrough$X3B + 2.031 * RyanYarbrough$HR) / (RyanYarbrough$AB + RyanYarbrough$BB - RyanYarbrough$IBB + RyanYarbrough$SF + RyanYarbrough$HBP)

RyanYarbrough$wOBA <- RyanYarbroughwOBA
RyanYarbrough$wOBA

summary(RyanYarbrough$wOBA)
```

